name: Deploy to GithubPages

on:
  push:
    branches: ["master"]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  deploy-to-gh-pages:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: 'npm'

      - name: Install Packages
        run: |
          npm ci

      - name: Build prod
        run: |
          npm run build

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist
